source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'AFNetworking'
pod 'MZFormSheetController'
pod 'MarqueeLabel'
pod 'Wit'
pod 'UINavigationItem+Loading'
pod 'M13ProgressSuite'
pod 'RESideMenu'
pod 'SCLAlertView-Objective-C'
pod 'YLProgressBar'
pod 'JTCalendar'
pod 'Masonry'
pod 'Socket.IO-Client-Swift', '~> 2.0'
pod 'XLRemoteImageView'

pod 'PromiseKit-AFNetworking'